// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = SECRET_DEVICE_LOGIN_NAME;
const char SSID[]               = SECRET_SSID;
const char PASS[]               = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;

void onAvgsensorChange();
void onSensorChange();
void onSensor1Change();
void onSensor2Change();
void onRelayChange();

int avgsensor;
int sensor;
int sensor1;
int sensor2;
bool relay;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(avgsensor, READWRITE, 1 * SECONDS, onAvgsensorChange);
  ArduinoCloud.addProperty(sensor, READWRITE, 1 * SECONDS, onSensorChange);
  ArduinoCloud.addProperty(sensor1, READWRITE, 1 * SECONDS, onSensor1Change);
  ArduinoCloud.addProperty(sensor2, READWRITE, 1 * SECONDS, onSensor2Change);
  ArduinoCloud.addProperty(relay, READWRITE, ON_CHANGE, onRelayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
